### ISSUE TITLE
Make sure app isn't rotatable

### ISSUE THREAD

**Issue by AEFeinstein** [AEFeinstein/MiniScoreboard#15]
Autotester rotated it, thought that wasn't possible.

**Comment by AEFeinstein** [comment]
This was the associated crash

```
 FATAL EXCEPTION: main
 Process: com.gelakinetic.miniscoreboard, PID: 14065
 java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
    at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1538)
    at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1556)
    at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:696)
    at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:662)
    at android.support.v4.app.DialogFragment.show(DialogFragment.java:143)
    at com.gelakinetic.miniscoreboard.MainActivity$3.onDataChange(MainActivity.java:211)
    at com.google.firebase.database.Query$1.onDataChange(Unknown Source)
    at com.google.android.gms.internal.zzakg.zza(Unknown Source)
    at com.google.android.gms.internal.zzalg.zzcxk(Unknown Source)
    at com.google.android.gms.internal.zzalj$1.run(Unknown Source)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5417)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by AEFeinstein** [comment]
Definitely as locked as I can make it

**Comment by AEFeinstein** [comment]
Nope, the activity when you sign out is rotatable

**Comment by AEFeinstein** [comment]
Can't prevent the createSignInIntentBuilder() Activity from rotating.
